name: CI
on: [push]
jobs:
  standard-checks:
    name: Lint and Test
    runs-on: ubuntu-latest

    steps:
      - run: node -v
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.9.1'

      - run: node -v
      - name: Install packages
        run: npm ci
      - name: Run ESLint
        run: npm run ci:lint
      - name: Run tests
        run: npm run ci:test
